import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/css/globals.css";
import HomeIcon from "../assets/icons/svg/home-icon";
import Sidebar from "../components/layout/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { href: "/", label: "Home", icon: <HomeIcon /> },
  { href: "/", label: "Home", icon: <HomeIcon /> },
  { href: "/", label: "Home", icon: <HomeIcon /> },
  { href: "/", label: "Home", icon: <HomeIcon /> },
  { href: "/", label: "Home", icon: <HomeIcon /> },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-300 antialiased`}
      >
        <Sidebar items={items}>
          <div className="flex h-full w-full flex-col">{children}</div>
        </Sidebar>
      </body>
    </html>
  );
}
